# ##############################################################################
#
# Config for bacon
#
# All urls are the base paths only.
#
#     e.g USE http://example.co
#
#                 as opposed to:
#
#             http://example.com/path
#
# ##############################################################################

# ******************************************************************************
# PNC details
#
# ******************************************************************************
profile:
- name: "default"
  pnc:
      url: ""
      bifrostBaseurl: ""
  keycloak:
      url: ""
      realm: ""
      username: ""
      clientId: ""
  pig:
      kojiHubUrl: ""
      licenseServerUrl: ""
      indyUrl: ""
  da:
      url: ""
  rex:
      url: ""
# ******************************************************************************
# Authentication information
#
# Uncomment this section if you want to create / update / delete
# ******************************************************************************
#  keycloak:
#      url: ""
#      realm: ""
#      username: ""
#
#      # if regular user
#      clientId: ""
#
#      # if service account
#      clientSecret: ""
- name: "coolProfile"
  pnc:
      url: ""
      bifrostBaseurl: ""
# ******************************************************************************
# Authentication information
#
# Uncomment this section if you want to create / update / delete
# ******************************************************************************
#  keycloak:
#      url: ""
#      realm: ""
#      username: ""
#
#      # if regular user
#      clientId: ""
#
#      # if service account
#      clientSecret: ""
