name: Build snapshot version and upload to Maven Central

on:
  push:
    branches: [ "main" ]

jobs:
    call-snapshot-job:
      uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@v0.0.12
      with:
        project_name: 'project-ncl/bacon'
        # The junit:junit:4.12 is used in one of our tests to get the license.
        # Weirdly it needs to be present in our .m2/repository folder for the
        # test to pass. I thought it would be downloaded by the Maven resolver
        # directly.
        snapshot_deploy_command: mvn dependency:get -Dartifact=junit:junit:4.12 && mvn -B -V org.apache.maven.plugins:maven-source-plugin:jar-no-fork deploy
        java_version: 17
      secrets: inherit
