name: Build snapshot version and upload to Maven Central

on:
  push:
    branches: [ "main" ]

jobs:
    call-snapshot-job:
      uses: project-ncl/shared-github-actions/.github/workflows/maven-snapshot.yml@v0.0.10
      with:
        project_name: 'project-ncl/bacon'
        fetch_all_commits: true
      secrets: inherit
